In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import os

In [6]:
dir = os.getcwd() + '\\data'
df = pd.read_csv(dir+'\\train.csv')
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df = np.array(df)
m,n = df.shape
np.random.shuffle(df)

dfDev = df[0:1000].T
yDev = dfDev[0]
xDev = dfDev[1:n]

dfTrain = df[1000:m].T
yTrain = dfTrain[0]
xTrain = dfTrain[1:n]

In [ ]:
def init_params():
    w1 = np.random.rand(10,n-1)
    b1 = np.random.rand(10,1)
    w2 = np.random.rand(10,10)
    b2 = np.random.rand(10,1)
    return b1,w1,b2,w2

def ReLu(x):
    return np.maximum(0,x)

def softMax(x):
    return np.exp(x)/np.sum(np.exp(x))

def forward_prop(w1,b1,w2,b2,x):
    z1 = w1.dot(x) + b1
    a1 = ReLu(z1)
    z2 = w2.dot(z1) + b2
    a2 = softMax(z2)
    return z1,a1,z2,a2

def deriv_ReLu(x):
    return x > 0

def one_hot(y):
    oneHoty = np.zeros((y.size,y.max()+1))
    oneHoty[np.arange(y.size),y] = 1
    oneHoty = oneHoty.T
    return oneHoty

def back_prop(z1,a1,z2,a2,x,y):
    oneHoty = one_hot(y)
    dZ2 = a2 - oneHoty
    dW2 = 1 / y.size * dZ2.dot(a1.T)
    dB2 = 1 / y.size * np.sum(dZ2)
    dZ1 = w2.T.dot(dZ2) * deriv_ReLu(z1)
    dW1 = 1 / y.size * dZ1.dot(x.T)
    dB1 = 1 / y.size * np.sum(dZ1)
    return dW1,dB1,dW2,dB2

def update_params(w1,b1,w2,b2,dW1,dB1,dW2,dB2,alpha):
    w1 = w1 - dW1 * alpha
    b1 = b1 - dB1 * alpha
    w2 = w2 - dW2 * alpha
    b2 = b2 - dW2 * alpha
    return w1,b1,w2,b2